sprint 5
kgontsov/MovieQuiz-ios pull request #3
Opened 2023-03-09 13:04 UTC by kgontsov

2023-03-09 13:05 UTC, kgontsov commented
🫠

2023-03-10 08:18 UTC, protos17 requested changes

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    let alertPresenterDelegate: MovieQuizViewController
Нужно быть внимательным к делегатам, рекомендую сделать его weak var, а тип поставить UIViewController?, иначе без weak может оказаться цикл сильных ссылок

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +class AlertPresenter {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory: QuestionFactoryProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +            text: "Рейтинг этого фильма больше чем 6?",
Повторяющуюся строку рекомендую вынести в отдельную константу

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +            return totalAcc
UserDefaults поддерживает работу с примитивными типами, здесь можно упростить, написав userDefaults.double(forKey: Keys.total.rawValue)

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +            userDefaults.set(data, forKey: Keys.total.rawValue)
Здесь можно упростить userDefaults.set(newValue, forKey: Keys.total.rawValue)

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +            return count
Здесь можно упростить userDefaults.integer(forKey: Keys.total.rawValue)

2023-03-10 08:18 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +            userDefaults.set(data, forKey: Keys.gamesCount.rawValue)
Здесь можно упростить userDefaults.set(newValue, forKey: Keys.total.rawValue)

2023-03-10 19:49 UTC, kgontsov commented
Данил, спасибо за рекомендации, добавил в to do когда дедлайн перестанет маячить.

2023-03-10 20:01 UTC, kgontsov commented on MovieQuiz/Services/QuestionFactory.swift
> +            text: "Рейтинг этого фильма больше чем 6?",
Не уверен что правильно понял, заменить 

> text: "Рейтинг этого фильма больше чем 6?"

 на константу в которой будет: "Рейтинг этого фильма больше чем 6?" и подставлять
уже её?

2023-03-10 20:03 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +            text: "Рейтинг этого фильма больше чем 6?",
Ну да, она же повторяется

2023-03-11 11:08 UTC, protos17 requested changes

2023-03-11 11:08 UTC, protos17 commented on MovieQuiz/Helpers/UIColor+Extensions.swift
>         static var ypRed: UIColor { UIColor(named: "ypRed") ?? UIColor.red }
В Assets.Colors у тебя написано как ypred", рекомендую цвета и там и там написать одинаково, чтобы они соответствовали друг другу.

2023-03-11 13:11 UTC, kgontsov commented on MovieQuiz/Helpers/UIColor+Extensions.swift
>         static var ypRed: UIColor { UIColor(named: "ypRed") ?? UIColor.red }
@protos17 в том то и дело, что у меня показывает нормально (скрин 1), но при коммите ypRed и остальные превращаются в ypred, за исключение почему-то background, он остался с большой в assets даже после переименования (скрин 2) [https://imgur.com/a/ke5nsFW](url) =/

2023-03-11 20:16 UTC, protos17 approved these changes

2023-03-11 20:32 UTC, merged